Update publish.yml

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -19,11 +19,17 @@ jobs:
           node-version: '18'
           cache: 'npm'
 
+      - name: List Files for Debugging
+        run: ls -la
+
+      - name: Check package-lock.json
+        run: cat package-lock.json || echo "package-lock.json not found"
+
       - name: Clear npm Cache
         run: npm cache clean --force
 
       - name: Install Dependencies
-        run: npm ci
+        run: npm ci || npm install
 
       - name: Build
         run: npm run build
